# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tools.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btools.proto\"\x1f\n\x08ToolList\x12\x13\n\x04tool\x18\x01 \x03(\x0b\x32\x05.Tool\"\x93\x01\n\x04Tool\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x15\n\x05units\x18\x03 \x02(\x0e\x32\x06.Units\x12%\n\rflat_end_tool\x18\x04 \x01(\x0b\x32\x0c.FlatEndToolH\x00\x12%\n\rball_end_tool\x18\x05 \x01(\x0b\x32\x0c.BallEndToolH\x00\x42\n\n\x08\x65nd_type\"\x7f\n\x0b\x46latEndTool\x12\x15\n\x05units\x18\x01 \x02(\x0e\x32\x06.Units\x12\x16\n\x0eshaft_diameter\x18\x02 \x01(\x02\x12\x15\n\rhead_diameter\x18\x03 \x02(\x02\x12\x15\n\rflutes_length\x18\x04 \x01(\x02\x12\x13\n\x0btaper_angle\x18\x05 \x01(\x02\"\x98\x01\n\x0b\x42\x61llEndTool\x12\x15\n\x05units\x18\x01 \x02(\x0e\x32\x06.Units\x12\x16\n\x0eshaft_diameter\x18\x02 \x01(\x02\x12\x15\n\rhead_diameter\x18\x03 \x02(\x02\x12\x17\n\x0f\x66lutes_diameter\x18\x04 \x01(\x02\x12\x15\n\rflutes_length\x18\x05 \x01(\x02\x12\x13\n\x0btaper_angle\x18\x06 \x01(\x02*2\n\x05Units\x12\x11\n\rUNITS_UNKNOWN\x10\x00\x12\x06\n\x02MM\x10\x01\x12\x06\n\x02\x43M\x10\x02\x12\x06\n\x02IN\x10\x03*;\n\x07\x45ndType\x12\x14\n\x10\x45ND_TYPE_UNKNOWN\x10\x00\x12\x0c\n\x08\x46LAT_END\x10\x01\x12\x0c\n\x08\x42\x41LL_END\x10\x02'
)

_UNITS = _descriptor.EnumDescriptor(
  name='Units',
  full_name='Units',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNITS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=482,
  serialized_end=532,
)
_sym_db.RegisterEnumDescriptor(_UNITS)

Units = enum_type_wrapper.EnumTypeWrapper(_UNITS)
_ENDTYPE = _descriptor.EnumDescriptor(
  name='EndType',
  full_name='EndType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='END_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLAT_END', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BALL_END', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=534,
  serialized_end=593,
)
_sym_db.RegisterEnumDescriptor(_ENDTYPE)

EndType = enum_type_wrapper.EnumTypeWrapper(_ENDTYPE)
UNITS_UNKNOWN = 0
MM = 1
CM = 2
IN = 3
END_TYPE_UNKNOWN = 0
FLAT_END = 1
BALL_END = 2



_TOOLLIST = _descriptor.Descriptor(
  name='ToolList',
  full_name='ToolList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tool', full_name='ToolList.tool', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=46,
)


_TOOL = _descriptor.Descriptor(
  name='Tool',
  full_name='Tool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Tool.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Tool.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='units', full_name='Tool.units', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flat_end_tool', full_name='Tool.flat_end_tool', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_end_tool', full_name='Tool.ball_end_tool', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='end_type', full_name='Tool.end_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=49,
  serialized_end=196,
)


_FLATENDTOOL = _descriptor.Descriptor(
  name='FlatEndTool',
  full_name='FlatEndTool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='units', full_name='FlatEndTool.units', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shaft_diameter', full_name='FlatEndTool.shaft_diameter', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='head_diameter', full_name='FlatEndTool.head_diameter', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flutes_length', full_name='FlatEndTool.flutes_length', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taper_angle', full_name='FlatEndTool.taper_angle', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=325,
)


_BALLENDTOOL = _descriptor.Descriptor(
  name='BallEndTool',
  full_name='BallEndTool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='units', full_name='BallEndTool.units', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shaft_diameter', full_name='BallEndTool.shaft_diameter', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='head_diameter', full_name='BallEndTool.head_diameter', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flutes_diameter', full_name='BallEndTool.flutes_diameter', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flutes_length', full_name='BallEndTool.flutes_length', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taper_angle', full_name='BallEndTool.taper_angle', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=480,
)

_TOOLLIST.fields_by_name['tool'].message_type = _TOOL
_TOOL.fields_by_name['units'].enum_type = _UNITS
_TOOL.fields_by_name['flat_end_tool'].message_type = _FLATENDTOOL
_TOOL.fields_by_name['ball_end_tool'].message_type = _BALLENDTOOL
_TOOL.oneofs_by_name['end_type'].fields.append(
  _TOOL.fields_by_name['flat_end_tool'])
_TOOL.fields_by_name['flat_end_tool'].containing_oneof = _TOOL.oneofs_by_name['end_type']
_TOOL.oneofs_by_name['end_type'].fields.append(
  _TOOL.fields_by_name['ball_end_tool'])
_TOOL.fields_by_name['ball_end_tool'].containing_oneof = _TOOL.oneofs_by_name['end_type']
_FLATENDTOOL.fields_by_name['units'].enum_type = _UNITS
_BALLENDTOOL.fields_by_name['units'].enum_type = _UNITS
DESCRIPTOR.message_types_by_name['ToolList'] = _TOOLLIST
DESCRIPTOR.message_types_by_name['Tool'] = _TOOL
DESCRIPTOR.message_types_by_name['FlatEndTool'] = _FLATENDTOOL
DESCRIPTOR.message_types_by_name['BallEndTool'] = _BALLENDTOOL
DESCRIPTOR.enum_types_by_name['Units'] = _UNITS
DESCRIPTOR.enum_types_by_name['EndType'] = _ENDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ToolList = _reflection.GeneratedProtocolMessageType('ToolList', (_message.Message,), {
  'DESCRIPTOR' : _TOOLLIST,
  '__module__' : 'tools_pb2'
  # @@protoc_insertion_point(class_scope:ToolList)
  })
_sym_db.RegisterMessage(ToolList)

Tool = _reflection.GeneratedProtocolMessageType('Tool', (_message.Message,), {
  'DESCRIPTOR' : _TOOL,
  '__module__' : 'tools_pb2'
  # @@protoc_insertion_point(class_scope:Tool)
  })
_sym_db.RegisterMessage(Tool)

FlatEndTool = _reflection.GeneratedProtocolMessageType('FlatEndTool', (_message.Message,), {
  'DESCRIPTOR' : _FLATENDTOOL,
  '__module__' : 'tools_pb2'
  # @@protoc_insertion_point(class_scope:FlatEndTool)
  })
_sym_db.RegisterMessage(FlatEndTool)

BallEndTool = _reflection.GeneratedProtocolMessageType('BallEndTool', (_message.Message,), {
  'DESCRIPTOR' : _BALLENDTOOL,
  '__module__' : 'tools_pb2'
  # @@protoc_insertion_point(class_scope:BallEndTool)
  })
_sym_db.RegisterMessage(BallEndTool)


# @@protoc_insertion_point(module_scope)
